=== moise-lang/moise/src/main/resources/xml/os.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:moise="https://moise-lang.github.io/os"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://moise-lang.github.io/os">

    <xsd:element name="organisational-specification" type="moise:osType"/>

    <xsd:complexType name="osType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties"               type="moise:propertiesType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="structural-specification" type="moise:ssType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="functional-specification" type="moise:fsType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="normative-specification"  type="moise:nsType"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string"/>
        <xsd:attribute name="os-version" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="ssType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="role-definitions">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="role" type="moise:roleDefType"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="link-types">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="1" name="link-type">
                            <xsd:complexType>
                                <xsd:attribute name="id" type="xsd:string" use="required"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="group-specification" type="moise:groupSpecificationType" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="fsType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="scheme">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
                        <xsd:element maxOccurs="1" minOccurs="1" name="goal" type="moise:goalDefType"/>

                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="accountability-agreement" type="moise:accountabilityAgreementType"/>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="notification-policy" type="moise:notificationPolicyType"/>

                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="mission" type="moise:missionType"/>
                    </xsd:sequence>

                    <xsd:attribute name="id" type="xsd:string"/>
                    <!-- xsd:attribute name="monitoring-scheme" type="xsd:string"> </xsd:attribute -->
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="missionType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="1" name="goal">
                <xsd:complexType>
                    <xsd:attribute name="id" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="preferred">
                <xsd:complexType>
                    <xsd:attribute name="mission" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="min" type="xsd:nonNegativeInteger"/>
        <xsd:attribute name="max" type="xsd:nonNegativeInteger"/>
    </xsd:complexType>

    <xsd:complexType name="nsType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="norm">
                <xsd:complexType>
                    <xsd:attribute name="id" type="xsd:string" use="required" />
                    <xsd:attribute name="condition" type="xsd:string" use="optional" />
                    <xsd:attribute name="role" type="xsd:string" use="required"/>
                    <xsd:attribute name="type" type="moise:deonticType" use="required"/>
                    <xsd:attribute name="mission" type="xsd:string" use="required"/>
                    <xsd:attribute name="time-constraint" type="xsd:string" use="optional"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="npl-norms" type="xsd:string" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="propertiesType">
        <xsd:sequence maxOccurs="unbounded" minOccurs="1">
            <xsd:element name="property">
                <xsd:complexType>
                    <xsd:attribute name="id" type="xsd:string" use="required"/>
                    <xsd:attribute name="value" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="roleDefType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="extends">
                <xsd:complexType>
                    <xsd:attribute name="role" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="scopeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="intra-group"/>
            <xsd:enumeration value="inter-group"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="cardinalityObjectType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="role"/>
            <xsd:enumeration value="group"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="groupSpecificationType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="roles">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="1" name="role">
                            <xsd:complexType>
                                <xsd:attribute name="id" type="xsd:string"/>
                                <xsd:attribute name="min" type="xsd:nonNegativeInteger" use="optional"/>
                                <xsd:attribute name="max" type="xsd:nonNegativeInteger" use="optional"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="links">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="1" name="link">
                            <xsd:complexType>
                                <xsd:attribute name="from" type="xsd:string"/>
                                <xsd:attribute name="to" type="xsd:string"/>
                                <xsd:attribute name="type" type="xsd:string"/>
                                <xsd:attribute default="intra-group" name="scope"             type="moise:scopeType"/>
                                <xsd:attribute default="false"       name="extends-subgroups" type="xsd:boolean"/>
                                <xsd:attribute default="false" name="bi-dir" type="xsd:boolean"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element maxOccurs="unbounded" minOccurs="0" name="subgroups">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="0"
                            name="include-group-specification">
                            <xsd:complexType>
                                <xsd:attribute name="uri" type="xsd:string"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="group-specification" type="moise:groupSpecificationType"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element maxOccurs="1" minOccurs="0" name="formation-constraints">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="cardinality">
                            <xsd:complexType>
                                <xsd:attribute name="min" type="xsd:nonNegativeInteger"         use="optional"/>
                                <xsd:attribute name="max" type="xsd:nonNegativeInteger"         use="optional"/>
                                <xsd:attribute name="object" type="moise:cardinalityObjectType" use="required"/>
                                <xsd:attribute name="id" type="xsd:string" use="required"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="compatibility">
                            <xsd:complexType>
                                <xsd:attribute name="from" type="xsd:string" use="required"/>
                                <xsd:attribute name="to" type="xsd:string" use="required"/>
                                <xsd:attribute default="intra-group" name="scope"        type="moise:scopeType"/>
                                <xsd:attribute default="false" name="extends-subgroups"  type="xsd:boolean"/>
                                <xsd:attribute default="false" name="bi-dir" type="xsd:boolean"/>
                                <xsd:attribute name="type" type="xsd:string"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="min" type="xsd:nonNegativeInteger" use="optional"/>
        <xsd:attribute name="max" type="xsd:nonNegativeInteger" use="optional"/>
        <!-- xsd:attribute name="monitoring-scheme" type="xsd:string"/ -->
    </xsd:complexType>

    <xsd:complexType name="planType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="1" name="goal" type="moise:goalDefType"/>
        </xsd:sequence>
        <xsd:attribute name="operator" type="moise:planOperatorType" use="required"/>
        <xsd:attribute name="success-rate" type="xsd:double" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="goalDefType">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="argument"   type="moise:argumentType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="depends-on" type="moise:dependOnType"/>
            <xsd:element maxOccurs="1"         minOccurs="0" name="plan"       type="moise:planType"/>
        </xsd:sequence>
        <xsd:attribute name="id"       type="xsd:string"             use="required"/>
        <xsd:attribute name="min"      type="xsd:nonNegativeInteger" use="optional"/>
        <xsd:attribute name="ds"       type="xsd:string"             use="optional"/>
        <xsd:attribute name="type"     type="moise:goalType"/>
        <xsd:attribute name="ttf"      type="xsd:string"             use="optional"/>
        <xsd:attribute name="location" type="xsd:string"             use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="accountabilityAgreementType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="context-goal" type="moise:goalDefType"/>
          <xsd:element maxOccurs="unbounded" minOccurs="1" name="account-template" type="moise:accountTemplateType"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="target" type="xsd:string" use="required"/>
        <xsd:attribute name="condition" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="notificationPolicyType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
          <xsd:element maxOccurs="unbounded" minOccurs="1" name="report" type="moise:exceptionSpecificationType"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="target" type="xsd:string" use="required"/>
        <xsd:attribute name="condition" type="xsd:string" use="required"/>
        <xsd:attribute name="type" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="exGoalDefType">
        <xsd:complexContent>
            <xsd:extension base="moise:goalDefType">
                <xsd:attribute name="when" type="xsd:string" use="optional"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="accountTemplateType">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="account-argument" type="moise:argArityType"/>
           <xsd:element maxOccurs="unbounded" minOccurs="0" name="requesting-goal" type="moise:exGoalDefType"/>
           <xsd:element maxOccurs="1" minOccurs="1" name="accounting-goal" type="moise:exGoalDefType"/>
           <xsd:element maxOccurs="unbounded" minOccurs="0" name="treatment-goal" type="moise:exGoalDefType"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="exceptionSpecificationType">
        <xsd:sequence>
           <xsd:element maxOccurs="unbounded" minOccurs="0" name="argument" type="moise:argArityType"/>
           <xsd:element maxOccurs="unbounded" minOccurs="1" name="raise-goal" type="moise:exGoalDefType"/>
           <xsd:element maxOccurs="unbounded" minOccurs="1" name="handle-goal" type="moise:exGoalDefType"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required" />
    </xsd:complexType>
    
    <xsd:complexType name="argArityType">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="arity" type="xsd:integer" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="argumentType">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="value" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="dependOnType">
        <xsd:attribute name="goal" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="planOperatorType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="sequence"/>
            <xsd:enumeration value="choice"/>
            <xsd:enumeration value="parallel"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="goalType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="performance"/>
            <xsd:enumeration value="achievement"/>
            <xsd:enumeration value="maintenance"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="deonticType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="obligation"/>
            <xsd:enumeration value="permission"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== moise-lang/moise/examples/robustness/atm/src/org/atm-os.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet href="https://moise-lang.github.io/xml/os.xsl" type="text/xsl" ?>

<organisational-specification
    id="atm" os-version="1.0"

    xmlns="https://moise-lang.github.io/os"
    
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://moise.sourceforge.net/os https://moise-lang.github.io/xml/os.xsd">

    <structural-specification>

        <role-definitions>
            <role id="atmHandler" />
            <role id="requestHandler" />
            <role id="reader" />
            <role id="parser" />
            <role id="moneyKeeper" />
        </role-definitions>

        <group-specification id="atm_group">
            <roles>
                <role id="atmHandler" min="1" max="1" />
                <role id="requestHandler" min="1" max="1" />
                <role id="reader" min="1" max="1" />
                <role id="parser" min="1" max="1" />
                <role id="moneyKeeper" min="1" max="1" />
            </roles>
        </group-specification>

    </structural-specification>



    <functional-specification>

        <scheme id="atm_sch">

            <goal id="withdraw">
                <plan operator="sequence">
                    <goal id="obtainAmount">
                        <plan operator="sequence">
                            <goal id="getAmountAsString" />
                            <goal id="parseAmount" />
                        </plan>
                    </goal>
                    <goal id="provideMoney" />
                </plan>
            </goal>

            <notification-policy id="np1" target="parseAmount"  condition="failed(_,parseAmount)"  type="exception">
                <report id="nan">
                    <argument id="index" arity="1" />
                    <raise-goal id="raiseNan"/>
                    <handle-goal id="recoverFromNan" />
                </report>
            </notification-policy>

            <notification-policy id="np2" target="recoverFromNan" condition="failed(_,recoverFromNan)"  type="exception">
                <report id="amountUnavailable">
                    <raise-goal id="raiseAmountUnavailable"/>
                    <handle-goal id="retryLater" />
                </report>
            </notification-policy>

            <mission id="mGetAmountAsString" min="1" max="1">
                <goal id="getAmountAsString" />
            </mission>
            <mission id="mParseAmount" min="1" max="1">
                <goal id="parseAmount" />
                <goal id="raiseNan" />
            </mission>
            <mission id="mObtainAmount" min="1" max="1">
                <goal id="obtainAmount" />
                <goal id="raiseAmountUnavailable" />
                <goal id="recoverFromNan" />
            </mission>
            <mission id="mProvideMoney" min="1" max="1">
                <goal id="provideMoney" />
            </mission>
            <mission id="mWithdraw" min="1" max="1">
                <goal id="withdraw" />
                <goal id="retryLater" />
            </mission>

        </scheme>

    </functional-specification>

    <normative-specification>
        <norm id="n1" type="obligation" role="atmHandler"
            mission="mWithdraw" />
        <norm id="n2" type="obligation" role="requestHandler"
            mission="mObtainAmount" />
        <norm id="n3" type="obligation" role="reader"
            mission="mGetAmountAsString" />
        <norm id="n4" type="obligation" role="parser"
            mission="mParseAmount" />
        <norm id="n5" type="obligation" role="moneyKeeper"
            mission="mProvideMoney" />
    </normative-specification>

</organisational-specification>

=== moise-lang/moise/examples/exceptions/production_cell/src/org/production-cell-os.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet href="https://moise-lang.github.io/xml/os.xsl" type="text/xsl" ?>

<organisational-specification
    id="production_cell" os-version="1.0"

    xmlns="https://moise-lang.github.io/os"
    
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://moise-lang.github.io/os https://moise-lang.github.io/os.xsd">

    <structural-specification>

        <role-definitions>
            <role id="feedBelt" />
            <role id="elevatingRotaryTable" />
            <role id="robot" />
            <role id="press" />
            <role id="depositBelt" />
        </role-definitions>

        <group-specification id="production_cell_group">
            <roles>
                <role id="feedBelt" min="1" max="1" />
                <role id="elevatingRotaryTable" min="1" max="1" />
                <role id="robot" min="1" max="1" />
                <role id="press" min="1" max="1" />
                <role id="depositBelt" min="1" max="1" />
            </roles>
        </group-specification>

    </structural-specification>

    <functional-specification>

        <scheme id="production_cell_scheme">

            <goal id="producePlate">
                <plan operator="sequence">
                    <goal id="conveyPlateToTable" ttf="5 seconds" />
                    <goal id="grabFromTableSetup">
                        <plan operator="parallel">
                            <goal id="turnTableMoveUp" />
                            <goal id="extendArm1" />
                        </plan>
                    </goal>
                    <goal id="grabPlateFromBelt" />
                    <goal id="unloadTable">
                        <plan operator="parallel">
                            <goal id="turnTableMoveDown" />
                            <goal id="movePlateOnPress" />
                        </plan>
                    </goal>
                    <goal id="releasePlateOnPress" />
                    <goal id="pressAndRetractArm1">
                        <plan operator="parallel">
                            <goal id="movePressDownUp" ttf="5 seconds" />
                            <goal id="retractArm1" />
                        </plan>
                    </goal>
                    <goal id="turnRobot" />
                    <goal id="extendArm2" />
                    <goal id="grabPlateFromPress" />
                    <goal id="movePlateOnBelt" />
                    <goal id="releasePlateOnBelt" />
                    <goal id="storePlate">
                        <plan operator="parallel">
                            <goal id="retractArm2" />
                            <goal id="conveyPlateToDeposit" />
                        </plan>
                    </goal>
                </plan>
            </goal>
            
            <notification-policy id="npStock" target="conveyPlateToTable"
                                    condition="scheme_id(S) &amp; unfulfilled(obligation(_,_,done(S,conveyPlateToTable,_),_))"  type="exception">
                <report id="exStock">
                    <argument id="availablePlates" arity="1" />
                    <raise-goal id="notifyRemainingStock" />
                    <handle-goal id="slowDownProduction" when="raised(exStock,_,Args) &amp; .member(availablePlates(N),Args) &amp; N &lt;= 10" />
                </report>
            </notification-policy>
        
            <notification-policy id="npMotor" target="turnTableMoveUp" condition="scheme_id(S) &amp; failed(S,turnTableMoveUp)"  type="exception">
                <report id="exMotor">
                    <argument id="motorNumber" arity="1" />
                    <raise-goal id="notifyStoppedMotorNumber" />
                    <handle-goal id="motorFix">
                        <plan operator="sequence">
                            <goal id="scheduleTableMotorFix" />
                            <goal id="pauseProduction" />
                        </plan>
                    </handle-goal>
                </report>
            </notification-policy>
            
            <notification-policy id="npPress" target="movePressDownUp"
                                    condition="scheme_id(S) &amp; unfulfilled(obligation(_,_,done(S,movePressDownUp,_),_))"  type="exception">
                <report id="exHuman">
                    <argument id="slowdownCode" arity="1" />
                    <argument id="humanCoords"  arity="2" />
                    <raise-goal id="explainSlowdownReason" />
                    <handle-goal id="emergencyStop" when="raised(exHuman,_,Args) &amp; .member(humanCoords(X,Y),Args) &amp; X &lt; 2 &amp; Y &lt; 3"/>
                </report>
            </notification-policy>

            <mission id="mFeedBelt" min="1" max="1">
                <goal id="conveyPlateToTable" />
                <goal id="notifyRemainingStock" />
            </mission>
            <mission id="mElevatingRotaryTable" min="1" max="1">
                <goal id="turnTableMoveUp" />
                <goal id="turnTableMoveDown" />
                <goal id="notifyStoppedMotorNumber" />
            </mission>
            <mission id="mRobot" min="1" max="1">
                <goal id="extendArm1" />
                <goal id="grabPlateFromBelt" />
                <goal id="movePlateOnPress" />
                <goal id="releasePlateOnPress" />
                <goal id="retractArm1" />
                <goal id="turnRobot" />
                <goal id="extendArm2" />
                <goal id="grabPlateFromPress" />
                <goal id="movePlateOnBelt" />
                <goal id="releasePlateOnBelt" />
                <goal id="retractArm2" />
                <goal id="slowDownProduction" />
                <goal id="scheduleTableMotorFix" />
                <goal id="pauseProduction" />
                <goal id="emergencyStop" />
            </mission>
            <mission id="mPress" min="1" max="1">
                <goal id="movePressDownUp" />
                <goal id="explainSlowdownReason" />
            </mission>
            <mission id="mDepositBelt" min="1" max="1">
                <goal id="conveyPlateToDeposit" />
            </mission>

        </scheme>

    </functional-specification>

    <normative-specification>
        <norm id="n1" type="obligation" role="feedBelt"
            mission="mFeedBelt" />
        <norm id="n2" type="obligation" role="elevatingRotaryTable"
            mission="mElevatingRotaryTable" />
        <norm id="n3" type="obligation" role="robot"
            mission="mRobot" />
        <norm id="n4" type="obligation" role="press"
            mission="mPress" />
        <norm id="n5" type="obligation" role="depositBelt"
            mission="mDepositBelt" />
    </normative-specification>

</organisational-specification>
