=== moise-lang/moise/src/main/resources/xml/os.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:moise="https://moise-lang.github.io/os"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://moise-lang.github.io/os">

    <xsd:element name="organisational-specification" type="moise:osType"/>

    <xsd:complexType name="osType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties"               type="moise:propertiesType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="structural-specification" type="moise:ssType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="functional-specification" type="moise:fsType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="normative-specification"  type="moise:nsType"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string"/>
        <xsd:attribute name="os-version" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="ssType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="role-definitions">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="role" type="moise:roleDefType"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="link-types">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="1" name="link-type">
                            <xsd:complexType>
                                <xsd:attribute name="id" type="xsd:string" use="required"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="group-specification" type="moise:groupSpecificationType" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="fsType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="scheme">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
                        <xsd:element maxOccurs="1" minOccurs="1" name="goal" type="moise:goalDefType"/>

                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="accountability-agreement" type="moise:accountabilityAgreementType"/>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="notification-policy" type="moise:notificationPolicyType"/>

                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="mission" type="moise:missionType"/>
                    </xsd:sequence>

                    <xsd:attribute name="id" type="xsd:string"/>
                    <!-- xsd:attribute name="monitoring-scheme" type="xsd:string"> </xsd:attribute -->
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="missionType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="1" name="goal">
                <xsd:complexType>
                    <xsd:attribute name="id" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="preferred">
                <xsd:complexType>
                    <xsd:attribute name="mission" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="min" type="xsd:nonNegativeInteger"/>
        <xsd:attribute name="max" type="xsd:nonNegativeInteger"/>
    </xsd:complexType>

    <xsd:complexType name="nsType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="norm">
                <xsd:complexType>
                    <xsd:attribute name="id" type="xsd:string" use="required" />
                    <xsd:attribute name="condition" type="xsd:string" use="optional" />
                    <xsd:attribute name="role" type="xsd:string" use="required"/>
                    <xsd:attribute name="type" type="moise:deonticType" use="required"/>
                    <xsd:attribute name="mission" type="xsd:string" use="required"/>
                    <xsd:attribute name="time-constraint" type="xsd:string" use="optional"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="npl-norms" type="xsd:string" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="propertiesType">
        <xsd:sequence maxOccurs="unbounded" minOccurs="1">
            <xsd:element name="property">
                <xsd:complexType>
                    <xsd:attribute name="id" type="xsd:string" use="required"/>
                    <xsd:attribute name="value" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="roleDefType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="extends">
                <xsd:complexType>
                    <xsd:attribute name="role" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="scopeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="intra-group"/>
            <xsd:enumeration value="inter-group"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="cardinalityObjectType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="role"/>
            <xsd:enumeration value="group"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="groupSpecificationType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="roles">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="1" name="role">
                            <xsd:complexType>
                                <xsd:attribute name="id" type="xsd:string"/>
                                <xsd:attribute name="min" type="xsd:nonNegativeInteger" use="optional"/>
                                <xsd:attribute name="max" type="xsd:nonNegativeInteger" use="optional"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="links">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="1" name="link">
                            <xsd:complexType>
                                <xsd:attribute name="from" type="xsd:string"/>
                                <xsd:attribute name="to" type="xsd:string"/>
                                <xsd:attribute name="type" type="xsd:string"/>
                                <xsd:attribute default="intra-group" name="scope"             type="moise:scopeType"/>
                                <xsd:attribute default="false"       name="extends-subgroups" type="xsd:boolean"/>
                                <xsd:attribute default="false" name="bi-dir" type="xsd:boolean"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element maxOccurs="unbounded" minOccurs="0" name="subgroups">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="0"
                            name="include-group-specification">
                            <xsd:complexType>
                                <xsd:attribute name="uri" type="xsd:string"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="group-specification" type="moise:groupSpecificationType"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element maxOccurs="1" minOccurs="0" name="formation-constraints">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="cardinality">
                            <xsd:complexType>
                                <xsd:attribute name="min" type="xsd:nonNegativeInteger"         use="optional"/>
                                <xsd:attribute name="max" type="xsd:nonNegativeInteger"         use="optional"/>
                                <xsd:attribute name="object" type="moise:cardinalityObjectType" use="required"/>
                                <xsd:attribute name="id" type="xsd:string" use="required"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="compatibility">
                            <xsd:complexType>
                                <xsd:attribute name="from" type="xsd:string" use="required"/>
                                <xsd:attribute name="to" type="xsd:string" use="required"/>
                                <xsd:attribute default="intra-group" name="scope"        type="moise:scopeType"/>
                                <xsd:attribute default="false" name="extends-subgroups"  type="xsd:boolean"/>
                                <xsd:attribute default="false" name="bi-dir" type="xsd:boolean"/>
                                <xsd:attribute name="type" type="xsd:string"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="min" type="xsd:nonNegativeInteger" use="optional"/>
        <xsd:attribute name="max" type="xsd:nonNegativeInteger" use="optional"/>
        <!-- xsd:attribute name="monitoring-scheme" type="xsd:string"/ -->
    </xsd:complexType>

    <xsd:complexType name="planType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="1" name="goal" type="moise:goalDefType"/>
        </xsd:sequence>
        <xsd:attribute name="operator" type="moise:planOperatorType" use="required"/>
        <xsd:attribute name="success-rate" type="xsd:double" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="goalDefType">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="argument"   type="moise:argumentType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="depends-on" type="moise:dependOnType"/>
            <xsd:element maxOccurs="1"         minOccurs="0" name="plan"       type="moise:planType"/>
        </xsd:sequence>
        <xsd:attribute name="id"       type="xsd:string"             use="required"/>
        <xsd:attribute name="min"      type="xsd:nonNegativeInteger" use="optional"/>
        <xsd:attribute name="ds"       type="xsd:string"             use="optional"/>
        <xsd:attribute name="type"     type="moise:goalType"/>
        <xsd:attribute name="ttf"      type="xsd:string"             use="optional"/>
        <xsd:attribute name="location" type="xsd:string"             use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="accountabilityAgreementType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="context-goal" type="moise:goalDefType"/>
          <xsd:element maxOccurs="unbounded" minOccurs="1" name="account-template" type="moise:accountTemplateType"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="target" type="xsd:string" use="required"/>
        <xsd:attribute name="condition" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="notificationPolicyType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
          <xsd:element maxOccurs="unbounded" minOccurs="1" name="report" type="moise:exceptionSpecificationType"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="target" type="xsd:string" use="required"/>
        <xsd:attribute name="condition" type="xsd:string" use="required"/>
        <xsd:attribute name="type" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="exGoalDefType">
        <xsd:complexContent>
            <xsd:extension base="moise:goalDefType">
                <xsd:attribute name="when" type="xsd:string" use="optional"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="accountTemplateType">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="account-argument" type="moise:argArityType"/>
           <xsd:element maxOccurs="unbounded" minOccurs="0" name="requesting-goal" type="moise:exGoalDefType"/>
           <xsd:element maxOccurs="1" minOccurs="1" name="accounting-goal" type="moise:exGoalDefType"/>
           <xsd:element maxOccurs="unbounded" minOccurs="0" name="treatment-goal" type="moise:exGoalDefType"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="exceptionSpecificationType">
        <xsd:sequence>
           <xsd:element maxOccurs="unbounded" minOccurs="0" name="argument" type="moise:argArityType"/>
           <xsd:element maxOccurs="unbounded" minOccurs="1" name="raise-goal" type="moise:exGoalDefType"/>
           <xsd:element maxOccurs="unbounded" minOccurs="1" name="handle-goal" type="moise:exGoalDefType"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required" />
    </xsd:complexType>
    
    <xsd:complexType name="argArityType">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="arity" type="xsd:integer" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="argumentType">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="value" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="dependOnType">
        <xsd:attribute name="goal" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="planOperatorType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="sequence"/>
            <xsd:enumeration value="choice"/>
            <xsd:enumeration value="parallel"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="goalType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="performance"/>
            <xsd:enumeration value="achievement"/>
            <xsd:enumeration value="maintenance"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="deonticType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="obligation"/>
            <xsd:enumeration value="permission"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== moise-lang/moise/examples/specifications/ReorgGr.xml
<?xml version="1.0" encoding="UTF-8"?>
<organisational-specification
    id="ReorgGr"
    os-version="0.4"

    xmlns='http://moise.sourceforge.net/os'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:schemaLocation='http://moise.sourceforge.net/os http://moise.sourceforge.net/xml/os.xsd'>

    <structural-specification>
        <role-definitions>
            <role id="Reorg" />

            <role id="Selector">          <extends role="Reorg"/>     </role>
            <role id="Historian">         <extends role="Reorg"/>     </role>
            <role id="Designer">          <extends role="Reorg"/>     </role>
            <role id="OrgParticipant">    <extends role="Designer"/>  </role>
            <role id="OrgManager"/>
            <role id="Monitor">           <extends role="Reorg"/>     </role>
            <role id="ReorgExpert">       <extends role="Designer"/>  </role>
            <role id="Monitored"/>
        </role-definitions>

        <group-specification id="reorgGr">
            <roles>
                <role id="Selector"   min="1" max="1" />
                <role id="Historian"  min="1" max="1" />
                <role id="OrgManager" min="1" max="1" />
                <role id="OrgParticipant"/>
                <role id="Monitor"/>
                <role id="ReorgExpert"/>
            </roles>
            <links>
                <link from="OrgManager" to="soc" type="authority" scope="intra-group" extends-subgroups="false" bi-dir="false"/>
                <link from="Reorg" to="OrgManager" type="communication" scope="intra-group" extends-subgroups="false" bi-dir="false"/>
                <link from="Monitor" to="Monitored" type="authority" scope="inter-group" extends-subgroups="false" bi-dir="false"/>
                <link from="Reorg" to="Reorg" type="communication" scope="intra-group" extends-subgroups="false" bi-dir="false"/>
            </links>
            <formation-constraints>
                <compatibility from="soc" to="OrgParticipant" type="compatibility" scope="intra-group" extends-subgroups="false" bi-dir="true"/>
                <compatibility from="soc" to="OrgParticipant" type="compatibility" scope="inter-group" extends-subgroups="false" bi-dir="true"/>
                <compatibility from="OrgManager" to="Historian" type="compatibility" scope="intra-group" extends-subgroups="false" bi-dir="true"/>
            </formation-constraints>
        </group-specification>
    </structural-specification>

    <functional-specification>
        <scheme id="reorganization" >
            <goal id="reorganization">
                <plan operator="sequence" >
                    <goal id="monitoring"/>
                    <goal id="design">
                        <plan operator="sequence" >
                            <goal id="invitation"/>
                            <goal id="waitDes">
                                <plan operator="parallel" >
                                    <goal id="expertDes"/>
                                    <goal id="practiceDes"/>
                                </plan>
                            </goal>
                        </plan>
                    </goal>
                    <goal id="selection"/>
                    <goal id="implementation"/>
                </plan>
            </goal>

            <mission id="m1" min="1">
                <goal id="invitation"/>
                <goal id="implementation"/>
                <goal id="design"/>
                <goal id="waitDes"/>
            </mission>
            <mission id="m2">
                <goal id="monitoring"/>
            </mission>
            <mission id="m4">
                <goal id="expertDes"/>
            </mission>
            <mission id="m5">
                <goal id="practiceDes"/>
                <preferred mission="m2"/>
            </mission>
            <mission id="m6" min="1">
                <goal id="selection"/>
            </mission>
        </scheme>
    </functional-specification>

    <normative-specification>
        <norm id="n1" type="obligation" role="OrgManager"     mission="m1" />
        <norm id="n2" type="permission" role="OrgParticipant" mission="m5" />
        <norm id="n3" type="obligation" role="Monitor"        mission="m2" />
        <norm id="n4" type="obligation" role="Selector"       mission="m6" />
        <norm id="n5" type="obligation" role="ReorgExpert"    mission="m4" />
    </normative-specification>
</organisational-specification>

=== moise-lang/moise/src/examples/test/groupwithoutrole.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet href="http://moise.sourceforge.net/xml/os.xsl" type="text/xsl" ?>

<organisational-specification 

    id="testsg"
    os-version="0.8"
  
    xmlns='http://moise.sourceforge.net/os'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:schemaLocation='http://moise.sourceforge.net/os
                        http://moise.sourceforge.net/xml/os.xsd' >
    
    <structural-specification>

        <role-definitions>
            <role id="r1" />
            <role id="r2" />
            <role id="r3" />
            <role id="r4" />
        </role-definitions>

        <group-specification id="g1" >

            <subgroups>
                <group-specification id="g2" min="1" max="1">
                    <roles>
                        <role id="r2" min="1"/>
                    </roles>
                    <subgroups>
                        <group-specification id="g3" min="1">
		                    <roles>
		                        <role id="r3" min="1"/>
		                    </roles>
                        </group-specification>
                    </subgroups>
                </group-specification>
                <group-specification id="g4" min="1" max="1">
		            <roles>
		                <role id="r4" min="1"/>
		            </roles>
                </group-specification>
            </subgroups>
        </group-specification>
    </structural-specification>



    <functional-specification>
        
    </functional-specification>

    <normative-specification>
       
    </normative-specification>
</organisational-specification>

=== moise-lang/moise/src/test/resources/cake-os-exception.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet href="https://moise-lang.github.io/xml/os.xsl" type="text/xsl" ?>

<organisational-specification
    id="atm" os-version="1.0"

    xmlns="https://moise-lang.github.io/os"
    
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://moise-lang.github.io/os https://moise-lang.github.io/os.xsd">

    <structural-specification>

        <role-definitions>
            <role id="baker" />
            <role id="apprentice" />
            <role id="customer" />
            <role id="supplier" />
        </role-definitions>

        <group-specification id="bakery">
            <roles>
                <role id="baker" min="1" max="1" />
                <role id="apprentice" min="1" max="1" />
                <role id="supplier" min="1" max="1" />
                <role id="customer" min="1" max="1" />
            </roles>
        </group-specification>

    </structural-specification>

    <functional-specification>

        <scheme id="cake_sch">

            <goal id="haveCake">
                <plan operator="sequence">
                    <goal id="workspaceSetup">
                        <plan operator="parallel">
                            <goal id="provideIngredients" />
                            <goal id="switchOnOven" />
                        </plan>
                    </goal>
                    <goal id="mixIngredients" />
                    <goal id="bakeCake" />
                </plan>
            </goal>

            <notification-policy id="np1" target="provideIngredients" condition="scheme_id(S) &amp; failed(S,provideIngredients)">
                <report id="ingredientsUnavailable">
                    <argument id="missingIngredients" arity="1" />
                    <raise-goal id="notifyIngredientsUnavailability"/>
                    <handle-goal id="dealWithMissingIngredients" />
                </report>
            </notification-policy>

            <notification-policy id="np2" target="switchOnOven" condition="scheme_id(S) &amp; failed(S,switchOnOven)">
                <report id="ovenBroken">
                    <argument id="faultType" arity="1" />
                    <raise-goal id="notifyProblemWithOven" />
                    <handle-goal id="checkOven" />
                </report>
            </notification-policy>

            <notification-policy id="np2" target="workspaceSetup" condition="scheme_id(S) &amp; (failed(S,dealWithMissingIngredients) | failed(S,checkOven))">
                <report id="cakePreparationFailure">
                    <raise-goal id="notifyCakePreparationFailure" />
                    <handle-goal id="cancelOrder" />
                </report>
            </notification-policy>

            <mission id="mApprentice" min="1" max="1">
                <goal id="switchOnOven" />
                <goal id="bakeCake" />
                <goal id="notifyProblemWithOven" />
            </mission>
            <mission id="mSupplier" min="1" max="1">
                <goal id="provideIngredients" />
                <goal id="notifyIngredientsUnavailability" />
            </mission>
            <mission id="mBaker" min="1" max="1">
                <goal id="mixIngredients" />
                <goal id="dealWithMissingIngredients" />
                <goal id="checkOven" />
                <goal id="notifyCakePreparationFailure" />
            </mission>
            <mission id="mCustomer" min="1" max="1">
                <goal id="haveCake" />
                <goal id="cancelOrder" />
            </mission>

        </scheme>
    </functional-specification>

    <normative-specification>
        <norm id="n1" type="obligation" role="supplier"
            mission="mSupplier" />
        <norm id="n2" type="obligation" role="apprentice"
            mission="mApprentice" />
        <norm id="n3" type="obligation" role="baker" mission="mBaker" />
        <norm id="n4" type="obligation" role="customer" mission="mCustomer" />
    </normative-specification>

</organisational-specification>
