=== moise-lang/moise/src/main/resources/xml/os.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:moise="https://moise-lang.github.io/os"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://moise-lang.github.io/os">

    <xsd:element name="organisational-specification" type="moise:osType"/>

    <xsd:complexType name="osType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties"               type="moise:propertiesType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="structural-specification" type="moise:ssType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="functional-specification" type="moise:fsType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="normative-specification"  type="moise:nsType"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string"/>
        <xsd:attribute name="os-version" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="ssType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="role-definitions">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="role" type="moise:roleDefType"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="link-types">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="1" name="link-type">
                            <xsd:complexType>
                                <xsd:attribute name="id" type="xsd:string" use="required"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="group-specification" type="moise:groupSpecificationType" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="fsType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="scheme">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
                        <xsd:element maxOccurs="1" minOccurs="1" name="goal" type="moise:goalDefType"/>

                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="accountability-agreement" type="moise:accountabilityAgreementType"/>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="notification-policy" type="moise:notificationPolicyType"/>

                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="mission" type="moise:missionType"/>
                    </xsd:sequence>

                    <xsd:attribute name="id" type="xsd:string"/>
                    <!-- xsd:attribute name="monitoring-scheme" type="xsd:string"> </xsd:attribute -->
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="missionType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="1" name="goal">
                <xsd:complexType>
                    <xsd:attribute name="id" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="preferred">
                <xsd:complexType>
                    <xsd:attribute name="mission" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="min" type="xsd:nonNegativeInteger"/>
        <xsd:attribute name="max" type="xsd:nonNegativeInteger"/>
    </xsd:complexType>

    <xsd:complexType name="nsType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="norm">
                <xsd:complexType>
                    <xsd:attribute name="id" type="xsd:string" use="required" />
                    <xsd:attribute name="condition" type="xsd:string" use="optional" />
                    <xsd:attribute name="role" type="xsd:string" use="required"/>
                    <xsd:attribute name="type" type="moise:deonticType" use="required"/>
                    <xsd:attribute name="mission" type="xsd:string" use="required"/>
                    <xsd:attribute name="time-constraint" type="xsd:string" use="optional"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="npl-norms" type="xsd:string" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="propertiesType">
        <xsd:sequence maxOccurs="unbounded" minOccurs="1">
            <xsd:element name="property">
                <xsd:complexType>
                    <xsd:attribute name="id" type="xsd:string" use="required"/>
                    <xsd:attribute name="value" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="roleDefType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="extends">
                <xsd:complexType>
                    <xsd:attribute name="role" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="scopeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="intra-group"/>
            <xsd:enumeration value="inter-group"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="cardinalityObjectType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="role"/>
            <xsd:enumeration value="group"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="groupSpecificationType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="roles">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="1" name="role">
                            <xsd:complexType>
                                <xsd:attribute name="id" type="xsd:string"/>
                                <xsd:attribute name="min" type="xsd:nonNegativeInteger" use="optional"/>
                                <xsd:attribute name="max" type="xsd:nonNegativeInteger" use="optional"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="links">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="1" name="link">
                            <xsd:complexType>
                                <xsd:attribute name="from" type="xsd:string"/>
                                <xsd:attribute name="to" type="xsd:string"/>
                                <xsd:attribute name="type" type="xsd:string"/>
                                <xsd:attribute default="intra-group" name="scope"             type="moise:scopeType"/>
                                <xsd:attribute default="false"       name="extends-subgroups" type="xsd:boolean"/>
                                <xsd:attribute default="false" name="bi-dir" type="xsd:boolean"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element maxOccurs="unbounded" minOccurs="0" name="subgroups">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="0"
                            name="include-group-specification">
                            <xsd:complexType>
                                <xsd:attribute name="uri" type="xsd:string"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="group-specification" type="moise:groupSpecificationType"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element maxOccurs="1" minOccurs="0" name="formation-constraints">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="cardinality">
                            <xsd:complexType>
                                <xsd:attribute name="min" type="xsd:nonNegativeInteger"         use="optional"/>
                                <xsd:attribute name="max" type="xsd:nonNegativeInteger"         use="optional"/>
                                <xsd:attribute name="object" type="moise:cardinalityObjectType" use="required"/>
                                <xsd:attribute name="id" type="xsd:string" use="required"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element maxOccurs="unbounded" minOccurs="0" name="compatibility">
                            <xsd:complexType>
                                <xsd:attribute name="from" type="xsd:string" use="required"/>
                                <xsd:attribute name="to" type="xsd:string" use="required"/>
                                <xsd:attribute default="intra-group" name="scope"        type="moise:scopeType"/>
                                <xsd:attribute default="false" name="extends-subgroups"  type="xsd:boolean"/>
                                <xsd:attribute default="false" name="bi-dir" type="xsd:boolean"/>
                                <xsd:attribute name="type" type="xsd:string"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="min" type="xsd:nonNegativeInteger" use="optional"/>
        <xsd:attribute name="max" type="xsd:nonNegativeInteger" use="optional"/>
        <!-- xsd:attribute name="monitoring-scheme" type="xsd:string"/ -->
    </xsd:complexType>

    <xsd:complexType name="planType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="1" name="goal" type="moise:goalDefType"/>
        </xsd:sequence>
        <xsd:attribute name="operator" type="moise:planOperatorType" use="required"/>
        <xsd:attribute name="success-rate" type="xsd:double" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="goalDefType">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="argument"   type="moise:argumentType"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="depends-on" type="moise:dependOnType"/>
            <xsd:element maxOccurs="1"         minOccurs="0" name="plan"       type="moise:planType"/>
        </xsd:sequence>
        <xsd:attribute name="id"       type="xsd:string"             use="required"/>
        <xsd:attribute name="min"      type="xsd:nonNegativeInteger" use="optional"/>
        <xsd:attribute name="ds"       type="xsd:string"             use="optional"/>
        <xsd:attribute name="type"     type="moise:goalType"/>
        <xsd:attribute name="ttf"      type="xsd:string"             use="optional"/>
        <xsd:attribute name="location" type="xsd:string"             use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="accountabilityAgreementType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="context-goal" type="moise:goalDefType"/>
          <xsd:element maxOccurs="unbounded" minOccurs="1" name="account-template" type="moise:accountTemplateType"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="target" type="xsd:string" use="required"/>
        <xsd:attribute name="condition" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="notificationPolicyType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="properties" type="moise:propertiesType"/>
          <xsd:element maxOccurs="unbounded" minOccurs="1" name="report" type="moise:exceptionSpecificationType"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="target" type="xsd:string" use="required"/>
        <xsd:attribute name="condition" type="xsd:string" use="required"/>
        <xsd:attribute name="type" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="exGoalDefType">
        <xsd:complexContent>
            <xsd:extension base="moise:goalDefType">
                <xsd:attribute name="when" type="xsd:string" use="optional"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="accountTemplateType">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="account-argument" type="moise:argArityType"/>
           <xsd:element maxOccurs="unbounded" minOccurs="0" name="requesting-goal" type="moise:exGoalDefType"/>
           <xsd:element maxOccurs="1" minOccurs="1" name="accounting-goal" type="moise:exGoalDefType"/>
           <xsd:element maxOccurs="unbounded" minOccurs="0" name="treatment-goal" type="moise:exGoalDefType"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="exceptionSpecificationType">
        <xsd:sequence>
           <xsd:element maxOccurs="unbounded" minOccurs="0" name="argument" type="moise:argArityType"/>
           <xsd:element maxOccurs="unbounded" minOccurs="1" name="raise-goal" type="moise:exGoalDefType"/>
           <xsd:element maxOccurs="unbounded" minOccurs="1" name="handle-goal" type="moise:exGoalDefType"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required" />
    </xsd:complexType>
    
    <xsd:complexType name="argArityType">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="arity" type="xsd:integer" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="argumentType">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="value" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="dependOnType">
        <xsd:attribute name="goal" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="planOperatorType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="sequence"/>
            <xsd:enumeration value="choice"/>
            <xsd:enumeration value="parallel"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="goalType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="performance"/>
            <xsd:enumeration value="achievement"/>
            <xsd:enumeration value="maintenance"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="deonticType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="obligation"/>
            <xsd:enumeration value="permission"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== moise-lang/moise/examples/robustness/house-building-accountability/src/org/house-os.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet href="https://moise-lang.github.io/xml/os.xsl" type="text/xsl" ?>

<organisational-specification
    id="house" os-version="1.0"

    xmlns="https://moise-lang.github.io/os"
    
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://moise-lang.github.io/os https://moise-lang.github.io/os.xsd">

    <structural-specification>

        <role-definitions>
            <role id="house_owner" />
            <role id="engineer" />
            <role id="building_company" />
            <role id="site_prep_contractor">
                <extends role="building_company" />
            </role>
            <role id="bricklayer">
                <extends role="building_company" />
            </role>
            <role id="roofer">
                <extends role="building_company" />
            </role>
            <role id="window_fitter">
                <extends role="building_company" />
            </role>
            <role id="door_fitter">
                <extends role="building_company" />
            </role>
            <role id="plumber">
                <extends role="building_company" />
            </role>
            <role id="electrician">
                <extends role="building_company" />
            </role>
            <role id="painter">
                <extends role="building_company" />
            </role>
        </role-definitions>

        <group-specification id="house_group">
            <roles>
                <role id="house_owner" min="1" max="1" />
                <role id="site_prep_contractor" min="1" max="1" />
                <role id="bricklayer" min="1" max="2" />
                <role id="roofer" min="1" max="1" />
                <role id="window_fitter" min="1" max="1" />
                <role id="door_fitter" min="1" max="1" />
                <role id="plumber" min="1" max="1" />
                <role id="electrician" min="1" max="1" />
                <role id="painter" min="1" max="1" />
                <role id="engineer" min="1" max="1" />
            </roles>

            <links>
                <link from="house_owner" type="authority" to="building_company"
                    scope="intra-group" />
                <link from="building_company" type="communication"
                    to="house_owner" scope="intra-group" />
            </links>

            <formation-constraints>
                <compatibility from="building_company"
                    to="building_company" scope="intra-group" />
            </formation-constraints>

        </group-specification>
    </structural-specification>

    <functional-specification>
        <scheme id="build_house_sch">
            <goal id="house_built">
                <plan operator="sequence">
                    <goal id="site_prepared" ttf="20 minutes"
                        ds="prepare the site for the next tasks" />
                    <goal id="floors_laid" ttf="25 minutes" />
                    <goal id="walls_built" ttf="40 minutes" />
                    <goal id="rwd">
                        <plan operator="parallel">
                            <goal id="roof_built" ttf="10 seconds" />
                            <goal id="windows_fitted" ttf="5 seconds" />
                            <goal id="doors_fitted" ttf="5 seconds" />
                        </plan>
                    </goal>
                    <goal id="pee">
                        <plan operator="parallel">
                            <goal id="plumbing_installed" ttf="20 minutes" />
                            <goal id="electrical_system_installed" ttf="20 minutes" />
                            <goal id="exterior_painted" ttf="20 minutes" />
                        </plan>
                    </goal>
                    <goal id="interior_painted" ttf="30 minutes" />
                </plan>
            </goal>

            <accountability-agreement id="aaSitePreparation" target="site_prepared" condition="failed(_,site_prepared)">
                <account-template id="ec">
                    <account-argument id="errorCode" arity="1" />
                    <accounting-goal id="notify_site_problem" />
                    <treatment-goal id="restore_site" when="account(ec,_,[errorCode(flooding)])" />
                    <treatment-goal id="remove_remains" when="account(ec,_,[errorCode(archaeologicalRemains)])" />
                </account-template>
            </accountability-agreement>
            
            <accountability-agreement id="aaWindowDelay" target="windows_fitted" condition="scheme_id(S) &amp; unfulfilled(obligation(_,_,done(S,windows_fitted,_),_))">
                <account-template id="delay">
                    <account-argument id="weeksOfDelay" arity="1" />
                    <accounting-goal id="notify_windows_fitting_delay" />
                    <treatment-goal id="handle_windows_fitting_delay" when="account(delay,_,[weeksOfDelay(D)]) &amp; D &gt;=2" />
                </account-template>
            </accountability-agreement>

            <mission id="management_of_house_building" min="1" max="1">
                <goal id="house_built" />
                <goal id="handle_windows_fitting_delay" />
            </mission>
            <mission id="site_inspection" min="1" max="1">
                <goal id="restore_site" />
                <goal id="remove_remains" />
            </mission>
            <mission id="prepare_site" min="1" max="1">
                <goal id="site_prepared" />
                <goal id="notify_site_problem" />
            </mission>
            <mission id="lay_floors" min="1" max="1">
                <goal id="floors_laid" />
            </mission>
            <mission id="build_walls" min="1" max="1">
                <goal id="walls_built" />
            </mission>
            <mission id="build_roof" min="1" max="1">
                <goal id="roof_built" />
            </mission>
            <mission id="fit_windows" min="1" max="1">
                <goal id="windows_fitted" />
                <goal id="notify_windows_fitting_delay" />
            </mission>
            <mission id="fit_doors" min="1" max="1">
                <goal id="doors_fitted" />
            </mission>
            <mission id="install_plumbing" min="1" max="1">
                <goal id="plumbing_installed" />
            </mission>
            <mission id="install_electrical_system" min="1" max="1">
                <goal id="electrical_system_installed" />
            </mission>
            <mission id="paint_house" min="1" max="1">
                <goal id="exterior_painted" />
                <goal id="interior_painted" />
            </mission>
        </scheme>
    </functional-specification>

    <normative-specification>
        <norm id="n1" type="obligation" role="house_owner"
            mission="management_of_house_building" time-constraint="2 minutes" />
        <norm id="n2" type="obligation" role="site_prep_contractor"
            mission="prepare_site" />
        <norm id="n3" type="obligation" role="bricklayer"
            mission="lay_floors" />
        <norm id="n4" type="obligation" role="bricklayer"
            mission="build_walls" />
        <norm id="n5" type="obligation" role="roofer"
            mission="build_roof" />
        <norm id="n6" type="obligation" role="window_fitter"
            mission="fit_windows" />
        <norm id="n7" type="obligation" role="door_fitter"
            mission="fit_doors" />
        <norm id="n8" type="obligation" role="plumber"
            mission="install_plumbing" />
        <norm id="n9" type="obligation" role="electrician"
            mission="install_electrical_system" />
        <norm id="n10" type="obligation" role="painter"
            mission="paint_house" />
        <norm id="n11" type="obligation" role="engineer"
            mission="site_inspection" />
    </normative-specification>

</organisational-specification>

=== moise-lang/moise/examples/robustness/therapy/exceptions/src/org/therapy-os.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet href="https://moise-lang.github.io/xml/os.xsl" type="text/xsl" ?>

<organisational-specification
    id="therapy" os-version="1.0"

    xmlns="https://moise-lang.github.io/os"
    
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://moise-lang.github.io/os https://moise-lang.github.io/os.xsd">

    <structural-specification>

        <role-definitions>
            <role id="patient" />
            <role id="doctor" />
            <role id="pharmacist" />
        </role-definitions>

        <group-specification id="therapy_group">
            <roles>
                <role id="patient" min="1" max="1" />
                <role id="doctor" min="1" max="1" />
                <role id="pharmacist" min="1" max="1" />
            </roles>
        </group-specification>

    </structural-specification>

    <functional-specification>

        <scheme id="therapy_sch">

            <goal id="therapy">
                <plan operator="parallel">
                    <goal id="cpf">
                        <plan operator="sequence">
                            <goal id="consult" />
                            <goal id="prescribe" />
                            <goal id="fill_prescription" />
                        </plan>
                    </goal>
                    <goal id="follow_therapy" ttf="5 seconds" /> <!-- 1 second = 1 day in real life -->
                </plan>
            </goal>

            <notification-policy id="np1" target="follow_therapy" condition="unfulfilled(obligation(_,_,done(_,follow_therapy,_),_))" type="exception">

                <report id="exception_lost_request">
                    <argument id="date" arity="1" />
                    <raise-goal id="raise_exception_lost_request" when="not satisfied(_,prescribe)" /> 
                    <handle-goal id="handle_exception_lost_request" />
                </report>

                <report id="exception_no_delivery">
                    <argument id="date" arity="1" />
                    <argument id="doctor_name" arity="1" />
                    <raise-goal id="raise_exception_no_delivery" when="satisfied(_,prescribe) &amp; not raised(exception_lost_request,_,_)" /> 
                    <handle-goal id="handle_exception_no_delivery" when="satisfied(_,fill_prescription) &amp; not satisfied(_,handle_exception_no_delivery_no_fill)" /> 
                    <handle-goal id="handle_exception_no_delivery_no_fill" when="not satisfied(_,fill_prescription) &amp; not satisfied(_,handle_exception_no_delivery)" /> 
                </report>

                <report id="exception_missing_prescription">
                    <argument id="date" arity="1" />
                    <argument id="patient_name" arity="1" />
                    <raise-goal id="raise_exception_missing_prescription" when="satisfied(_,prescribe) &amp; failed(_,fill_prescription) &amp; not raised(exception_lost_request,_,_)" />
                    <handle-goal id="handle_exception_missing_prescription" />
                </report>

            </notification-policy>

            <mission id="mPatient" min="1" max="1">
                <goal id="consult" />
                <goal id="follow_therapy" />
                <goal id="raise_exception_lost_request" />
                <goal id="raise_exception_no_delivery" />
            </mission>
            
            <mission id="mDoctor" min="1" max="1">
                <goal id="prescribe" />
                <goal id="handle_exception_lost_request" />
                <goal id="handle_exception_missing_prescription" />
            </mission>
            
            <mission id="mPharmacist" min="1" max="1">
                <goal id="fill_prescription" />
                <goal id="handle_exception_no_delivery" />
                <goal id="handle_exception_no_delivery_no_fill" />
                <goal id="raise_exception_missing_prescription" />
            </mission>

        </scheme>

    </functional-specification>

    <normative-specification>
        <norm id="n1" type="obligation" role="patient"    mission="mPatient" />
        <norm id="n2" type="obligation" role="doctor"     mission="mDoctor" />
        <norm id="n3" type="obligation" role="pharmacist" mission="mPharmacist" />
    </normative-specification>

</organisational-specification>
